import { appendFile, mkdir, readdir, rename, rm, stat, writeFile as writeBytes } from "node:fs/promises";
import { homedir } from "node:os";
import path from "node:path";
import type { PluginServerContext } from "@getpaseo/plugin/server";
import { resolveFiles, writeFile, type StoredFile, type TodoError } from "../shared/contracts";
import { FILE_CHUNK_BYTES } from "../shared/limits";
import type { TodoDocument } from "../shared/schema";
import type { TodoLogger } from "./log";
import type { TodoStore } from "./store";

/** File ids are generated by `createId("file")`; anything else never becomes a directory name. */
const FILE_ID = /^file_[a-z0-9]+$/;
/** The bytes of a file still arriving; the finished file takes its real name. */
const PARTIAL = ".upload";
/** Room for the name on file systems that cap a name at 255 bytes. */
const NAME_MAX_BYTES = 200;
/**
 * How long a file no card references is kept. A file is uploaded when it is picked, well before
 * the card that will reference it is saved, and a launched agent may still open a file after the
 * card drops it.
 */
export const ORPHAN_GRACE_MS = 7 * 24 * 60 * 60 * 1000;

/**
 * Where attached files live: beside the daemon's own data, so agents on this host can open them.
 * The plugin process inherits `PASEO_HOME` from the daemon.
 */
export function defaultFileDirectory(): string {
  const home = process.env.PASEO_HOME || path.join(homedir(), ".paseo");
  return path.join(home, "plugin-data", "todo", "files");
}

/** A name that is safe as one path segment, keeping the extension an agent goes by. */
export function safeFileName(name: string): string {
  let clean = name.replace(/[\u0000-\u001f\u007f/\\]/g, "_").trim().replace(/^\.+/, "");
  if (!clean) clean = "file";
  if (Buffer.byteLength(clean) <= NAME_MAX_BYTES) return clean;
  const dot = clean.lastIndexOf(".");
  const extension = dot > 0 && clean.length - dot <= 16 ? clean.slice(dot) : "";
  let stem = clean.slice(0, clean.length - extension.length);
  while (stem && Buffer.byteLength(stem + extension) > NAME_MAX_BYTES) stem = [...stem].slice(0, -1).join("");
  return stem + extension;
}

async function finished(directory: string): Promise<StoredFile | null> {
  let entries: string[];
  try {
    entries = await readdir(directory);
  } catch {
    return null;
  }
  const name = entries.find((entry) => entry !== PARTIAL);
  if (!name) return null;
  const target = path.join(directory, name);
  const info = await stat(target);
  return { id: path.basename(directory), size: info.size, path: target };
}

async function sizeOf(file: string): Promise<number | null> {
  try {
    return (await stat(file)).size;
  } catch {
    return null;
  }
}

export type WriteOutcome = { status: "ok"; received: number; file?: StoredFile } | TodoError;

/**
 * Stores one piece of a file, in order. A piece at offset 0 starts the file over; any other piece
 * must continue exactly where the stored bytes end. The last piece renames the bytes to the file's
 * own name, so an agent never opens a half-written file, and repeating it after a lost reply
 * returns the finished file again.
 */
export async function writeFilePiece(
  input: { id: string; name: string; size: number; offset: number; data: string },
  root: string = defaultFileDirectory(),
): Promise<WriteOutcome> {
  if (!FILE_ID.test(input.id)) return { status: "invalid_input", message: "Unknown file id." };
  const bytes = Buffer.from(input.data, "base64");
  if (bytes.length > FILE_CHUNK_BYTES || input.offset + bytes.length > input.size) {
    return { status: "invalid_input", message: "The file piece does not fit the file." };
  }
  const directory = path.join(root, input.id);
  const partial = path.join(directory, PARTIAL);
  const end = input.offset + bytes.length;
  if (input.offset === 0) {
    await rm(directory, { recursive: true, force: true });
    await mkdir(directory, { recursive: true });
    await writeBytes(partial, bytes);
  } else {
    const held = await sizeOf(partial);
    if (held === null) {
      const done = await finished(directory);
      if (done && done.size === input.size && end === input.size) return { status: "ok", received: done.size, file: done };
    }
    if (held !== input.offset) {
      return { status: "conflict", message: "The file upload lost its place. Add the file again.", details: { received: held ?? 0 } };
    }
    await appendFile(partial, bytes);
  }
  if (end < input.size) return { status: "ok", received: end };
  const target = path.join(directory, safeFileName(input.name));
  await rename(partial, target);
  return { status: "ok", received: end, file: { id: input.id, size: input.size, path: target } };
}

/** The finished files of `ids`, in order; ids with no finished file are missing. */
export async function findFiles(ids: readonly string[], root: string = defaultFileDirectory()): Promise<{ files: StoredFile[]; missing: string[] }> {
  const files: StoredFile[] = [];
  const missing: string[] = [];
  for (const id of ids) {
    const file = FILE_ID.test(id) ? await finished(path.join(root, id)) : null;
    if (file) files.push(file);
    else missing.push(id);
  }
  return { files, missing };
}

export function referencedFileIds(document: TodoDocument): Set<string> {
  const ids = new Set<string>();
  for (const item of Object.values(document.workItems)) {
    for (const file of item.files) ids.add(file.id);
  }
  return ids;
}

/** Removes files no card references once they are older than the grace period. */
export async function pruneFiles(referenced: ReadonlySet<string>, now: number, root: string = defaultFileDirectory(), graceMs = ORPHAN_GRACE_MS): Promise<number> {
  let entries: string[];
  try {
    entries = await readdir(root);
  } catch {
    return 0;
  }
  let removed = 0;
  for (const entry of entries) {
    if (!FILE_ID.test(entry) || referenced.has(entry)) continue;
    const directory = path.join(root, entry);
    const modified = (await stat(directory).catch(() => null))?.mtimeMs;
    if (modified === undefined || now - modified < graceMs) continue;
    await rm(directory, { recursive: true, force: true });
    removed += 1;
  }
  return removed;
}

/**
 * Publishes `todo.files.write` and `todo.files.resolve`, and prunes orphaned files at start and
 * after each finished upload. Writes run one at a time, so two pieces never append at once.
 */
export function registerFileHandlers(deps: {
  server: Pick<PluginServerContext, "handle">;
  store: Pick<TodoStore, "read">;
  log: TodoLogger;
  directory?: string;
}): void {
  const root = deps.directory ?? defaultFileDirectory();
  let queue: Promise<unknown> = Promise.resolve();

  const prune = async () => {
    try {
      const read = await deps.store.read();
      if (read.status !== "ok") return;
      const removed = await pruneFiles(referencedFileIds(read.document), Date.now(), root);
      if (removed > 0) deps.log.info("files_pruned", { count: removed });
    } catch (error) {
      deps.log.warn("files_prune_failed", { message: error instanceof Error ? error.message : String(error) });
    }
  };

  deps.server.handle(writeFile, (input) => {
    const written = queue.then(async (): Promise<WriteOutcome> => {
      try {
        const outcome = await writeFilePiece(input, root);
        if (outcome.status === "ok" && outcome.file) void prune();
        return outcome;
      } catch (error) {
        deps.log.error("file_write_failed", { message: error instanceof Error ? error.message : String(error) });
        return { status: "document_invalid", message: "The file could not be written to disk." };
      }
    });
    queue = written;
    return written;
  });

  deps.server.handle(resolveFiles, async (input) => {
    try {
      const { files, missing } = await findFiles(input.ids, root);
      if (missing.length > 0) deps.log.warn("files_missing", { count: missing.length });
      return { status: "ok" as const, files, missing };
    } catch (error) {
      deps.log.error("files_resolve_failed", { message: error instanceof Error ? error.message : String(error) });
      return { status: "document_invalid" as const, message: "The attached files could not be read." };
    }
  });

  void prune();
}
