import { mkdir, readdir, rename, rm, stat, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import path from "node:path";
import type { PluginServerContext, PluginSettings } from "@getpaseo/plugin/server";
import { stageImages, type HostFile } from "../shared/contracts";
import type { TodoImagesSchema } from "../shared/images";
import type { TodoLogger } from "./log";

export type TodoImagesDocument = PluginSettings<typeof TodoImagesSchema>;

const EXTENSIONS: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/gif": "gif",
  "image/webp": "webp",
};

/** Image ids are generated by `createId("img")`; anything else never becomes a file name. */
const IMAGE_ID = /^img_[a-z0-9]+$/;

/**
 * Where staged images live: beside the daemon's own data, so agents on this host can open them.
 * The plugin process inherits `PASEO_HOME` from the daemon.
 */
export function defaultImageDirectory(): string {
  const home = process.env.PASEO_HOME || path.join(homedir(), ".paseo");
  return path.join(home, "plugin-data", "todo", "images");
}

/**
 * Writes the bytes of `ids` from the `todo-images` document to files an agent can open, and
 * returns them in order. Inline image blocks can drop out of a provider's context in later turns;
 * a path stays readable for the whole conversation. Files are named by image id and never
 * rewritten, so a retried launch sends the same paths. Ids without stored bytes are reported as
 * missing. Files whose image is gone from the document are removed on the way.
 */
export async function stageImageFiles(
  images: TodoImagesDocument,
  ids: readonly string[],
  directory: string = defaultImageDirectory(),
): Promise<{ files: HostFile[]; missing: string[] }> {
  const state = await images.read();
  if (state.status !== "ready") throw new Error(`The image store could not be read (${state.status}).`);
  const stored = state.values.images;
  await mkdir(directory, { recursive: true });
  const files: HostFile[] = [];
  const missing: string[] = [];
  for (const id of ids) {
    const image = stored[id];
    const extension = EXTENSIONS[image?.mimeType ?? ""];
    if (!image || !extension || !IMAGE_ID.test(id)) {
      missing.push(id);
      continue;
    }
    const target = path.join(directory, `${id}.${extension}`);
    const bytes = Buffer.from(image.data, "base64");
    if (!(await exists(target))) {
      // Written aside, then renamed, so an agent never opens a half-written file.
      const temporary = `${target}.${process.pid}.tmp`;
      await writeFile(temporary, bytes);
      await rename(temporary, target);
    }
    files.push({ id, fileName: image.name ?? `${id}.${extension}`, mimeType: image.mimeType, size: bytes.length, path: target });
  }
  await removeOrphans(directory, new Set(Object.keys(stored)));
  return { files, missing };
}

async function exists(file: string): Promise<boolean> {
  try {
    await stat(file);
    return true;
  } catch {
    return false;
  }
}

async function removeOrphans(directory: string, known: ReadonlySet<string>): Promise<void> {
  let entries: string[];
  try {
    entries = await readdir(directory);
  } catch {
    return;
  }
  for (const entry of entries) {
    const id = entry.split(".")[0] ?? "";
    // A temporary of a known id may belong to a write in flight, so only the id decides.
    if (!known.has(id) && IMAGE_ID.test(id)) await rm(path.join(directory, entry), { force: true });
  }
}

/**
 * Publishes `todo.images.stage`. Calls run one at a time: two launches of the same card would
 * otherwise race on one temporary file name.
 */
export function registerImageHandlers(deps: {
  server: Pick<PluginServerContext, "handle">;
  images: TodoImagesDocument;
  log: TodoLogger;
  directory?: string;
}): void {
  let queue: Promise<unknown> = Promise.resolve();
  deps.server.handle(stageImages, (input) => {
    const staged = queue.then(async () => {
      try {
        const { files, missing } = await stageImageFiles(deps.images, input.ids, deps.directory);
        if (missing.length > 0) deps.log.warn("images_missing", { count: missing.length });
        return { status: "ok" as const, files, missing };
      } catch (error) {
        deps.log.error("images_stage_failed", { message: error instanceof Error ? error.message : String(error) });
        return { status: "document_invalid" as const, message: "The images could not be written to disk." };
      }
    });
    queue = staged;
    return staged;
  });
}
